window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/25095437-ce843676';
window.___jsl.l=[];
window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/:session_prefix:_/sharebox/dialog"},":socialhost:":"https://plusone.google.com","plusone_m":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"root-1p":"https://clients6.google.com","root":"https://www.googleapis.com","xd3":"/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","auth":{"useInterimAuth":false}}});var gapi=window.gapi||{};gapi.client=window.gapi&&window.gapi.client||{};
(function(){var o=void 0,p=void 0,q="___jsl",G="h",l="l",H="m",r="ms",s="cu",I="c",J="cm",K="o",m="p",i="q",n="https://ssl.gstatic.com",L="/webclient/js",M="/webclient/jsx/",t="https://apis.google.com",u=".js",N="gcjs-3p",O=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?(\/[\w.,:!=/-]*)(\?[^#]*)?(#.*)?$/,v=/^[?#]([^&]*&)*jsh=([^&]*)/,w="d",j="r",P="f",k="m",x="n",Q="sync",R="callback",y="config",z="nodep",A="gapi.load: ",B=function(a,b){o&&o(a,b);throw A+a+(b&&" "+b);},C=function(a){p&&p(a);var b=window.console;
b&&b.warn(A+a)},S=function(a,b,d){a=a[G];if(b=b&&v.exec(b)||d&&v.exec(d))try{a=decodeURIComponent(b[2])}catch(f){C("Invalid hint "+b[2])}return a},D=function(a){a.sort();for(var b=0;b<a.length;)!a[b]||b&&a[b]==a[b-1]?a.splice(b,1):++b},T=function(a,b){for(var d=true,f=0,c=0,e,g;d&&(e=a[f])&&(g=b[c]);)e==g?++f:e<g&&(d=false),++c;return d&&!e},U=function(a){if(document.readyState!="loading")return false;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(a&&(a=a[Q],typeof a!="undefined"))return a;
for(var a=document.getElementsByTagName("meta"),b=0,d;d=a[b];++b)if("generator"==d.getAttribute("name")&&"blogger"==d.getAttribute("content"))return true;return false},V=function(a){var b=document.createElement("script");b.setAttribute("src",a);a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)},X=function(a,b,d,f,c){var e=d.shift(),g;g=e==j?n:e==k?f[r]||t:(g=d.shift())&&g.replace(/\/+$/,"");var h;e==j?(h=d.shift(),h=(h.indexOf(M)?L+"/":"")+h):h=d.shift();var i=e==w,W=i&&
d.shift()||N,d=i&&d.shift();if(e==w)c=h,h=W,a="/"+a.join(":")+(b.length?"!"+b.join(":"):"")+u+"?container="+h+"&c=2&jsload=0",c&&(a+="&r="+c),d=="d"&&(a+="&debug=1");else if(e==j||e==P)c=h,a=(c.indexOf("/")?"/":"")+c+"/"+a.join("__")+(b.length?"--"+b.join("__"):"")+u;else if(e==k||e==x)b=h,a=a.join(",").replace(/\./g,"_").replace(/-/g,"_"),a=b.replace("__features__",a),a=c[z]?a.replace("/d=1/","/d=0/"):a;else return C("Unknown hint type "+e),"";if(!g)return"";g+=a;a=g;b=f;if(c=f=O.exec(a))if(c=!/\.\.|\/\//.test(f[4]))b:if(c=
a,f=f[2],e==j)c=c.substr(0,n.length)==n;else if(e==k)f=b[r]||t,c=c.substr(0,f.length)==f;else{e=b[H];if(f&&e){e=e.split(",");b=0;for(c=e.length;b<c;++b)if(d=e[b],h=f.lastIndexOf(d),(h==0||d.charAt(0)=="."||f.charAt(h-1)==".")&&f.length-d.length==h){c=true;break b}}c=false}c||B("Invalid URI",a);return g},Y=function(a,b,d){(a[i]=a[i]||[]).push([b,d])},F=function(a){a[i]&&a[i].length>0&&(window.gapi.load||E).apply(null,a[i].shift())},E=function(a,b){var d,f={};typeof b!=="function"?(f=b||{},d=f[R]):
d=b;var c=window[q]=window[q]||{};if(c[m])Y(c,a,b);else{var e=a.split(":");f[z]||D(e);var g=c[l]=c[l]||[];D(g);var h=S(c,window.location.search,window.location.hash);h||B("No hint present","");var i=function(a){if(a)try{a()}catch(b){return b}return null};if(!T(e,g)){var h=h.split(";"),j=h[0]==k||h[0]==x?J:I,g=X(e,g,h,c,f);f[y]&&(c[s]=c[s]||[]).push(f[y]);if(g){c[m]=e;c[K]=1;c[j]=function(){delete c[m];delete c[j];var a=i(d);F(c);if(a)throw a;};[].push.apply(c[l],e);U(f)?document.write('<script src="'+
encodeURI(g)+'"><\/script>'):V(g);return}}f=i(d);F(c);if(f)throw f;}};gapi.loader={load:E}})();
gapi.load=window.___jsl&&window.___jsl.il&&window.gapi&&window.gapi.load||gapi.loader.load;
(window.gapi=window.gapi||{}).load=window.___jsl&&window.___jsl.il&&window.gapi.load||gapi.load;
gapi.load('googleapis.client:plusone', {'callback': window['__bsld']  });